on:
  push:
    tags:
      - prod-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: yarn
      - name: Publish
        run: yarn deploy
        env:
          VSCE_PAT: ${{ secrets.AZURE_TOKEN }}
